name: Build Windows

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar CMake
      # Configuramos la compilación en modo Release (optimizado)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Compilar
      # Ejecutamos la compilación real
      run: cmake --build ${{github.workspace}}/build --config Release